import { type NextPage } from 'next';
import Head from 'next/head';
import { useSession } from 'next-auth/react';
import { api } from '../utils/api';
import type { FC } from 'react';
import { NotAuthorized } from '../components/NotAuthorized';
import { Document, Page, pdfjs } from 'react-pdf';
import { useEffect } from 'react';

const Sort: NextPage = () => {
    const { data: sessionData } = useSession();

    if (!sessionData) {
        return <NotAuthorized />;
    }

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
                        Sort
                    </h1>

                    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
                        <DocumentViewer />
                    </div>
                </div>
            </main>
        </>
    );
};

export default Sort;

const DocumentViewer: FC = () => {
    const { data, isLoading } = api.file.getAll.useQuery();

    useEffect(() => {
        pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`;
    }, []);

    if (isLoading) {
        return <div>Loading...</div>;
    }

    return (
        <div>
            {data?.map((file) => (
                <div className="text-white" key={file.id}>
                    <div>
                        <Document file={file.url}>
                            <Page
                                pageNumber={1}
                                renderTextLayer={false}
                                renderAnnotationLayer={false}
                            />
                        </Document>
                    </div>
                </div>
            ))}
        </div>
    );
};
