import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useSession } from 'next-auth/react';
import { NotAuthorized } from '../components/NotAuthorized';

const Workflows: NextPage = () => {
    const { data: sessionData } = useSession();

    if (!sessionData) {
        return <NotAuthorized />;
    }

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
                        Workflows
                    </h1>

                    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
                        <Link
                            className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                            href="/upload"
                        >
                            <h3 className="text-2xl font-bold">
                                Upload Documents
                            </h3>
                            <div className="text-lg">
                                This is the upload tool. Upload a bunch of
                                resumes. Note that this only accepts PDFs.
                            </div>
                        </Link>
                        <Link
                            className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                            href="/sort"
                        >
                            <h3 className="text-2xl font-bold">Sort</h3>
                            <div className="text-lg">
                                This is the sort tool. PDFs that have not been
                                sorted are shown here. Swipe left to reject and
                                right to accept the interview request.
                            </div>
                        </Link>
                        <Link
                            className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                            href="/interview"
                        >
                            <h3 className="text-2xl font-bold">Interview</h3>
                            <div className="text-lg">
                                This is the interview tool. PDFs that have been
                                sorted into accepted are listed here. Search for
                                the name of the person and start the interview
                                process.
                            </div>
                        </Link>
                    </div>
                </div>
            </main>
        </>
    );
};

export default Workflows;
